# Generated by Django 5.0.4 on 2024-08-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsData',
            fields=[
                ('itemId', models.BigAutoField(primary_key=True, serialize=False)),
                ('itemName', models.CharField()),
                ('itemQuantity', models.IntegerField()),
            ],
        ),
    ]
