# Generated by Django 5.0.4 on 2024-08-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0003_rename_id_itemsdata_id_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_item', models.CharField()),
                ('quantity_item', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='ItemsData',
        ),
    ]
