# Generated by Django 5.0.4 on 2024-08-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0004_itemsinfo_delete_itemsdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportIfo',
            fields=[
                ('name_report_file', models.CharField(primary_key=True, serialize=False)),
                ('name_user', models.CharField()),
                ('time_upload_report', models.DateField()),
            ],
        ),
    ]
