# Generated by Django 5.0.4 on 2024-08-17 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0005_reportifo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReportIfo',
            new_name='ReportInfo',
        ),
    ]
