# Generated by Django 5.0.4 on 2024-08-17 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0006_rename_reportifo_reportinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportinfo',
            old_name='time_upload_report',
            new_name='date_upload_report',
        ),
    ]
